#!/bin/sh

# needed for "Save and Apply" to restart athan
uci -q batch <<-EOF >/dev/null
	del ucitrack.@athan[-1]
	add ucitrack athan
	set ucitrack.@athan[-1].exec="/usr/sbin/athan.sh"
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
