#!/bin/sh

# needed for "Save and Apply" to restart shairport-sync
uci -q batch <<-EOF >/dev/null
	del ucitrack.@shairport-sync[-1]
	add ucitrack shairport-sync
	set ucitrack.@shairport-sync[-1].exec="/usr/sbin/airspeaker.sh"
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
